// Standalone HTML for the recipe lookup page served at "/".
//
// Two ways to find a recipe:
//   - Browse the full list (fetched once from /api/list.json, a static index
//     generated by the CI pipeline; filtered client-side, so no server load).
//   - Type a namespace:id directly (also works for mod items not in the index).
//
// The UI is built with MUI (Material UI) loaded as UMD bundles from a CDN,
// driven by a small React app (React.createElement, so no build/JSX step).
export const RECIPE_PAGE_HTML = /* html */ `<!DOCTYPE html>
<html lang="ja">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>ModParks Recipe</title>
<style>
  html, body { margin: 0; background: #121212; }
</style>
<script crossorigin src="https://unpkg.com/react@18/umd/react.production.min.js"></script>
<script crossorigin src="https://unpkg.com/react-dom@18/umd/react-dom.production.min.js"></script>
<script crossorigin src="https://unpkg.com/@mui/material@5.15.20/umd/material-ui.production.min.js"></script>
</head>
<body>
  <div id="root"></div>
<script>
(function () {
  const e = React.createElement;
  const MUI = MaterialUI;
  const {
    ThemeProvider, createTheme, CssBaseline, Container, Box, Card, CardContent,
    Typography, TextField, MenuItem, Button, Stack, Link, CircularProgress,
    List, ListItemButton, ListItemText, Divider, Chip
  } = MUI;

  const theme = createTheme({ palette: { mode: 'dark', primary: { main: '#646cff' } } });
  const MAX_ROWS = 300; // cap rendered rows so a huge list stays responsive

  function splitId(full) {
    const i = full.indexOf(':');
    return i === -1 ? { ns: 'minecraft', id: full } : { ns: full.slice(0, i), id: full.slice(i + 1) };
  }

  function App() {
    const [ids, setIds] = React.useState(null);   // null = loading, [] = none/failed
    const [q, setQ] = React.useState('');
    const [fmt, setFmt] = React.useState('png');
    const [shown, setShown] = React.useState(null);
    const [status, setStatus] = React.useState('idle');

    React.useEffect(function () {
      fetch('/api/list.json')
        .then(function (r) { return r.ok ? r.json() : { ids: [] }; })
        .then(function (d) { setIds(Array.isArray(d.ids) ? d.ids : []); })
        .catch(function () { setIds([]); });
    }, []);

    const query = q.trim().toLowerCase();
    const filtered = ids ? (query ? ids.filter(function (x) { return x.toLowerCase().includes(query); }) : ids) : [];

    function open(full) {
      const p = splitId(full);
      const path = '/api/' + encodeURIComponent(p.ns) + '/' + encodeURIComponent(p.id) + '.' + fmt;
      setShown({ ns: p.ns, id: p.id, fmt: fmt, path: path, src: path + '?t=' + Date.now() });
      setStatus('loading');
    }

    function openTyped(ev) {
      ev.preventDefault();
      if (!query) return;
      // If the query looks like an id, show it directly (supports mod items).
      open(q.trim());
    }

    return e(Container, { maxWidth: 'md', sx: { py: 6 } },
      e(Typography, { variant: 'h4', gutterBottom: true, fontWeight: 700 }, 'ModParks Recipe'),
      e(Typography, { color: 'text.secondary', sx: { mb: 3 } },
        'アイテムを一覧から選ぶか、ID（例: minecraft:wooden_sword）を入力してレシピを表示します。'),

      e('form', { onSubmit: openTyped },
        e(Stack, { direction: { xs: 'column', sm: 'row' }, spacing: 1.5, sx: { mb: 2 } },
          e(TextField, { label: '検索 / ID入力', placeholder: 'wooden_sword', value: q, onChange: function (x) { setQ(x.target.value); }, autoFocus: true, fullWidth: true }),
          e(TextField, { label: '形式', select: true, value: fmt, onChange: function (x) { setFmt(x.target.value); }, sx: { width: { sm: 130 } } },
            e(MenuItem, { value: 'png' }, 'PNG'),
            e(MenuItem, { value: 'gif' }, 'GIF'),
            e(MenuItem, { value: 'jpg' }, 'JPG')),
          e(Button, { type: 'submit', variant: 'contained', size: 'large' }, '表示'))),

      // Preview card
      shown && e(Card, { variant: 'outlined', sx: { mb: 3 } },
        e(CardContent, { sx: { textAlign: 'center' } },
          e(Typography, { variant: 'h6', sx: { mb: 0.5, wordBreak: 'break-all' } }, shown.ns + ':' + shown.id),
          e(Typography, { variant: 'caption', color: 'text.secondary', sx: { display: 'block', mb: 2 } },
            'namespace: ' + shown.ns + ' / item: ' + shown.id + ' / ' + shown.fmt.toUpperCase()),
          status === 'loading' && e(CircularProgress, { size: 28 }),
          status === 'error' && e(Typography, { color: 'error' }, 'レシピが見つかりませんでした。'),
          e('img', {
            src: shown.src, alt: 'recipe',
            onLoad: function () { setStatus('ok'); },
            onError: function () { setStatus('error'); },
            style: {
              display: status === 'ok' ? 'inline-block' : 'none',
              imageRendering: 'pixelated', maxWidth: '100%', borderRadius: 6, background: '#1e1e1e'
            }
          }),
          status === 'ok' && e(Box, { sx: { mt: 1.5, fontSize: 13, wordBreak: 'break-all' } },
            e(Link, { href: shown.path }, location.origin + shown.path)))),

      // Recipe list
      e(Box, { sx: { display: 'flex', alignItems: 'center', gap: 1, mb: 1 } },
        e(Typography, { variant: 'subtitle1', fontWeight: 600 }, 'レシピ一覧'),
        ids && e(Chip, { size: 'small', label: filtered.length + (query ? ' / ' + ids.length : '') })),
      e(Card, { variant: 'outlined' },
        ids === null
          ? e(Box, { sx: { p: 3, textAlign: 'center' } }, e(CircularProgress, { size: 24 }))
          : ids.length === 0
            ? e(Box, { sx: { p: 3, textAlign: 'center', color: 'text.secondary' } }, '一覧を取得できませんでした（索引が未生成の可能性があります）。')
            : e(React.Fragment, null,
                e(List, { dense: true, sx: { maxHeight: 460, overflow: 'auto', py: 0 } },
                  filtered.slice(0, MAX_ROWS).map(function (full, i) {
                    return e(ListItemButton, { key: full, divider: i < Math.min(filtered.length, MAX_ROWS) - 1, onClick: function () { open(full); } },
                      e(ListItemText, { primary: full }));
                  })),
                filtered.length > MAX_ROWS && e(Box, { sx: { p: 1.5, textAlign: 'center', color: 'text.secondary', fontSize: 13 } },
                  '他 ' + (filtered.length - MAX_ROWS) + ' 件… 検索で絞り込んでください'))));
  }

  ReactDOM.createRoot(document.getElementById('root')).render(
    e(ThemeProvider, { theme: theme }, e(CssBaseline, null), e(App, null))
  );
})();
</script>
</body>
</html>`;
